/** Generated from the checked-in cloud macro atlas manifest. */
export const CLOUD_PROTECTED_CU_BASE_CONTRACT_WGSL = /* wgsl */ `
// Generated by scripts/generate-cloud-volume-atlas.mjs.
const CLOUD_EXTERIOR_PROTECTED_CU_BASE_ALTITUDE: f32 = 0.14893617;
`;
